{
 "title": "Delivery Velocity (require Jira and Gitlab data)",
 "tags": [
  "velocity",
  "user_value"
 ],
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Time Interval", "query": "Week : DAYOFWEEK, Month : DAY" },
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select distinct concat(name, ': ', board_id) from jira_boards"
   },
   {
    "name": "repo_id",
    "label": "Choose Repo",
    "query": "select distinct concat(name, ': ', gitlab_id) from gitlab_projects"
   }
  ]
 },
 "panels": [
  {
   "title": "Charts are organized by the Research & Development stages below",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n    <div style=\"display:inline-block;text-align:center;padding-top:10px;\">\n        <img border=\"0\" src=\"/grafana/public/img/lake/practice_process_delivery_velocity.png\" alt=\"R&D Process\" width=\"60%\">\n    </div>\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  create_time AS \"time\",\n  progress\nFROM ca_analysis\nWHERE\n  $__timeFilter(create_time)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/practice_cross_domain.png\" alt=\"Cross-stage\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px;color:#CCCCDC;\"><b>Cross-stage Metrics<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Requirement Lead Time (day)",
   "type": "stat",
   "description": "1. The average lead time of requirements.\n2. Lead time refers to the length of time from requirement creation to delivery.\n3. The requirements being calculated are filtered by \"requirement resolution time\" (time filter at the upper-right corner) and \"Jira board\"(\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  avg(lead_time/1440) as value\r\nfrom jira_issues ji\n  join jira_board_issues jbi on ji.issue_id = jbi.issue_id\r\nwhere \n  std_type = 'Requirement'\n  and std_status = 'Resolved'\n  and $__timeFilter(resolution_date)\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Requirement Lead Time (day)",
   "type": "stat",
   "description": "1. The lead time at which 80% requirements‘ lead time lies below it.\n2. The requirements being calculated are filtered by \"requirement resolution time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    ji.lead_time,\n    percent_rank() over (order by lead_time asc) as ranks\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect\n  now() as time,\n  max(lead_time/1440) as value\r\nfrom _ranks\r\nwhere \n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Requirement Lead Time over Time",
   "type": "graph",
   "description": "1. The average requirement lead time over time.\n2. The time granularity can be switched to Week or Month by \"Time Interval\" above. \n3. When Time Interval is set to \"Month\", the average_lead_time of \"2021-06-01\" refers to the average lead time of requirements whose resolution time falls under [2020-06-01, 2020-07-01).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Lead Time(day)" }
   ],
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select \n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\n    lead_time\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  timestamp(time) as time,\n  avg(lead_time/1440) as average_lead_time\r\nfrom _requirement\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Requirement Lead Time (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of requirement lead time. \n2. Each point refers to the percent rank of a lead time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    round(ji.lead_time/1440) as lead_time_day\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n  order by lead_time_day asc\n)\n\r\nselect \n  now() as time,\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "title": "Average Requirement Lead Time by Epic",
   "type": "barchart",
   "description": "The average lead time of requirements under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select\n    ji.issue_id,\n    epic_key,\n    ji.lead_time\n  from\n    jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    ji.std_type = 'Requirement'\n    and ji.std_status = 'Resolved'\n    and ji.epic_key is not null\n    and ji.epic_key != ''\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  now() as time,\n  epic_key as \"Epic Key\",\n  avg(lead_time/1440) as value\r\nfrom _requirement\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Average Requirement Lead Time by Status",
   "type": "barchart",
   "description": "The average time spent in each state of a requirement, including all history states that have been used.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "with operation_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.changelog_id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.issue_id\n\t\tjoin jira_board_issues jbi on ji.issue_id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n)\n\nSELECT\n  now() as time,\n\tfrom_string as \"Requirement Status\",\n\tavg(time_in_status)/1440 as \"Time in Status\"\nFROM operation_history\nGROUP BY 1,2\nORDER BY 3 desc"
    }
   ]
  },
  {
   "title": "Average Requirement Lead Time by Status in Last 2 Months",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.changelog_id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.issue_id\n\t\tjoin jira_board_issues jbi on ji.issue_id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tavg(time_in_status)/60 as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nlast_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as last_month\n),\n\nmonth_before_last_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as two_month_before\n),\n\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\ntwo_month_before_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT two_month_before from month_before_last_month) then time_in_status else null end as two_month_before\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT two_month_before from month_before_last_month)\n)\n\nSELECT\n\tnow() as time,\n\tmbr.two_month_before AS \"The Month Before Last\",\n\tlmr.last_month AS \"Last Month\",\n\tlmr.issue_status\nFROM last_month_record lmr\nleft join two_month_before_record mbr on lmr.issue_status = mbr.issue_status "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/1.png\" alt=\"No.1\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Requirement<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requirement Count",
   "type": "stat",
   "description": "1. Total number of requirements created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  count(*) as value\r\nfrom jira_issues ji\n  join jira_board_issues jbi on ji.issue_id = jbi.issue_id\r\nwhere \n  std_type = 'Requirement'\n  and created is not null \n  and $__timeFilter(created)\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "Requirement Count over Time",
   "type": "timeseries",
   "description": "1. The number of requirements created over time.\n2. The time granularity can be switched to week or month by \"Time Interval\" above. \n3. When Time Interval is set to \"month\", the requirement_count of \"2021-06-01\" refers to the number of requirements whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select\n    ji.issue_id AS id,\n    DATE_ADD(date(created), INTERVAL -$interval(date(created))+1 DAY) as time\n  from\n    jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and created is not null \n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n)\n\r\nselect\n  timestamp(time) as time,\n  count(distinct id) as requirement_count\r\nfrom _requirement\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Requirement Count by Epic",
   "type": "barchart",
   "description": "1. The number of requirements under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select\n    ji.issue_id,\n    ji.epic_key\n  from\n    jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and created is not null\n    and epic_key is not null\n    and epic_key != ''\n    and std_status = 'Resolved'\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  now() as time,\n  epic_key as \"Epic Key\",\n  count(*) as value\r\nfrom _requirement\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Delivered Requirement Count",
   "type": "stat",
   "description": "1. Number of requirements that have been delivered.\n2. A requirement is delivered when its status equals 'delivered'.\n3. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  now() as time,\n  count(*) as delivered_count\r\nfrom jira_issues ji\n  join jira_board_issues jbi on ji.issue_id = jbi.issue_id\r\nwhere \n  std_type = 'Requirement'\n  and ji.std_status = 'Resolved'\n  and $__timeFilter(created)\n  and jbi.board_id = $board_id"
    }
   ]
  },
  {
   "title": "Requirement Delivery Rate",
   "type": "stat",
   "description": "Delivered Requirement Count/Requirement Count (Total)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select\n    count(distinct ji.issue_id) as total_count,\n    count(distinct case when ji.std_status = 'Resolved' then ji.issue_id else null end) as delivered_count\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n)\n\n\r\nselect \n  now() as time,\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirement"
    }
   ]
  },
  {
   "title": "Requirement Delivery Rate over Time",
   "type": "timeseries",
   "description": "1. The requirement delivery rate over time.\n2. When Time Interval is set to \"month\", value \"requirement_delivery_rate\" of \"2021-06-01\" calculates the requirements whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select\n    DATE_ADD(date(created), INTERVAL -$interval(date(created))+1 DAY) as time,\n    count(distinct ji.issue_id) as total_count,\n    count(distinct case when ji.std_status = 'Resolved' then ji.issue_id else null end) as delivered_count\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n  group by 1\n)\n\n\r\nselect \n  timestamp(time) as time,\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirement\r\norder by 1"
    }
   ]
  },
  {
   "title": "Requirement Delivery Rate by Epic",
   "type": "barchart",
   "description": "The average delivery rate of requirements under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select\n    ji.epic_key as metric,\n    count(distinct ji.issue_id) as total_count,\n    count(distinct case when ji.std_status = 'Resolved' then ji.issue_id else null end) as delivered_count\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and epic_key is not null\n    and epic_key != ''\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n  group by 1\n)\n\n\r\nselect \n  now() as time,\n  metric,\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirement\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Avg Requirement Granunarity(Story Point)",
   "type": "stat",
   "description": "1. The average story point (workload) of requirements.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  avg(std_story_point) as value\r\nfrom jira_issues ji\n  join jira_board_issues jbi on ji.issue_id = jbi.issue_id\r\nwhere \n  std_type = 'Requirement'\n  and std_story_point != 0\n  and $__timeFilter(created)\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Requirement Granunarity(Story point)",
   "type": "stat",
   "description": "1. The story point/estimated hours at which 80% requirements' story point/estimated hours lies below it.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    std_story_point,\n    percent_rank() over (order by std_story_point asc) as ranks\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and std_story_point != 0\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n)\n\r\nselect\n  now() as time,\n  max(std_story_point) as value\r\nfrom _ranks\r\nwhere \n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Requirement Granularity over Time",
   "type": "graph",
   "description": "The average and 80th percentile requirement granularity over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Story Points" }
   ],
   "targets": [
    {
     "rawSql": "with _requirement as(\n  select \n    ji.issue_id,\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\n    std_story_point\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and std_story_point != 0\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  timestamp(time) as time,\n  avg(std_story_point) as average_story_point\r\nfrom _requirement\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Requirement Granularity (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of requirement granularity.\n2. Each point refers to the percent rank of a value of granularity.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    round(std_story_point) as std_story_point\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Requirement'\n    and std_story_point != 0\n    and $__timeFilter(created)\n    and jbi.board_id = $board_id\n  order by std_story_point asc\n)\n\r\nselect \n  now() as time,\n  lpad(std_story_point, 4, ' ') as metric,\n  percent_rank() over (order by std_story_point asc) as value\r\nfrom _ranks\r\norder by std_story_point asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 79 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/2.png\" alt=\"No.2\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Development<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Pull Request Review Time (day)",
   "type": "stat",
   "description": "1. Average PR/MR review time.\n2. PR/MR review time refers to the time between the creation time and merged time of a PR/MR.\n3. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  avg(TIMESTAMPDIFF(MINUTE,gitlab_created_at,merged_at))/1440 as value\nfrom gitlab_merge_requests\nWHERE\n  merged_at is not null\n  and $__timeFilter(gitlab_created_at)\n  and project_id = $repo_id"
    }
   ]
  },
  {
   "title": "80th Percentile Pull Request Review Time(day)",
   "type": "stat",
   "description": "1. The 80th percentile PR/MR review time.\n2. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    TIMESTAMPDIFF(SECOND,gitlab_created_at,merged_at)/86400 as metric,\n    percent_rank() over (order by TIMESTAMPDIFF(MINUTE,gitlab_created_at,merged_at) asc) as ranks\n  from gitlab_merge_requests\n  WHERE\n    merged_at is not null\n    and $__timeFilter(gitlab_created_at)\n    and project_id = $repo_id\n  )\n  \nselect\n  now() as time,\n  max(metric) as value\nfrom _ranks\nwhere \n  ranks <= 0.8\ngroup by 1"
    }
   ]
  },
  {
   "title": "Pull Request Review Time over Time",
   "type": "timeseries",
   "description": "1. The average and 80th percentile PR/MR review time over time.\n2. The time granularity can be switched to week or month by \"Time Interval\" above. \n3. When Time Interval is set to \"month\", the average review time of \"2021-06-01\" refers to the review time of PR/MR whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with reviewed_mr as(\n  select\n    DATE_ADD(date(gitlab_created_at), INTERVAL -$interval(date(gitlab_created_at))+1 DAY) as time,\n    TIMESTAMPDIFF(SECOND,first_comment_time,merged_at)/86400 as review_time\n  from gitlab_merge_requests\n  WHERE\n    merged_at is not null\n    and $__timeFilter(gitlab_created_at)\n    and project_id = $repo_id\n)\n\nselect \n  timestamp(time) as time,\n  avg(review_time) as \"Average Review Time\"\nfrom reviewed_mr\ngroup by 1\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Commit Count",
   "type": "stat",
   "description": "1. Total number of commits created.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  count(*) as value\nFROM gitlab_commits\nWHERE\n  $__timeFilter(authored_date)\n  and project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Commit Count over Time",
   "type": "timeseries",
   "description": "1. Number of commits created over time.\n2. When Time Interval is set to \"month\", the commit_count\" of \"2021-06-01\" calculates the commits whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _commits as(\n  SELECT\n    DATE_ADD(date(authored_date), INTERVAL -$interval(date(authored_date))+1 DAY) as time,\n    count(*) as commit_count\n  FROM gitlab_commits\n  WHERE\n    $__timeFilter(authored_date)\n    and project_id = $repo_id\n  group by 1\n)\n\nSELECT \n  timestamp(time) as time,\n  commit_count as \"Commit Count\"\nFROM _commits\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Commit Count by Repo",
   "type": "graph",
   "description": "The number of commits from different repos.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  gp.name as metric,\n  count(*) as value\nFROM gitlab_commits gc\n  join gitlab_projects gp on gc.project_id = gp.gitlab_id\nWHERE\n  $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1,2\norder by 1"
    }
   ]
  },
  {
   "title": "Commit Count by Author",
   "type": "barchart",
   "description": "The number of commits from different commit authors.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  gc.author_name as \"Author Name\",\n  count(*) as value\nFROM gitlab_commits gc \n  join gitlab_projects gp on gc.project_id = gp.gitlab_id\nWHERE\n  $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1,2\norder by 3 desc\nlimit 20"
    }
   ]
  },
  {
   "title": "Added LOC",
   "type": "stat",
   "description": "1. Sum of the number of added lines of code under all commits.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  sum(additions) as value\nFROM gitlab_commits gc\n  join gitlab_projects gp on gc.project_id = gp.gitlab_id \nWHERE\n  message not like '%Merge branch%'\n  and $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deleted LOC",
   "type": "stat",
   "description": "1. Sum of the number of deleted lines of code under all commits.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  sum(deletions) as value\nFROM gitlab_commits gc\n  join gitlab_projects gp on gc.project_id = gp.gitlab_id \nWHERE\n  message not like '%Merge branch%'\n  and $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Added and Deleted LOC over Time",
   "type": "timeseries",
   "description": "Added/deleted number of lines of code over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with loc as(\n  SELECT\n    DATE_ADD(date(authored_date), INTERVAL -$interval(date(authored_date))+1 DAY) as time,\n    sum(additions) as added_LOC,\n    sum(deletions) as deleted_LOC\n  FROM gitlab_commits\n  WHERE\n    message not like '%Merge branch%'\n    and $__timeFilter(authored_date)\n    and project_id = $repo_id\n  group by 1\n)\n\nSELECT \n  timestamp(time) as time,\n  added_LOC as \"Added LOC\",\n  deleted_LOC as \"Deleted LOC\"\nFROM loc\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Added and Deleted LOC by Author",
   "type": "barchart",
   "description": "The number of added/deleted LOC from different commit authors.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  sum(additions) as \"Added LOC\",\n  sum(deletions) as \"Removed LOC\",\n  gc.author_name\nFROM gitlab_commits gc \n  join gitlab_projects gp on gc.project_id = gp.gitlab_id\nWHERE\n  author_name is not null\n  and message not like '%Merge branch%'\n  and $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1,4\norder by 2 desc\nlimit 20"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 113 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/3.png\" alt=\"No.3\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Test<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Bug Age (day)",
   "type": "stat",
   "description": "1. The average bug age.\n2. Bug age refers to the length of time from bug creation to resolution.\n3. The bugs being calculated are filtered by \"bug resolution time\" (time filter at the upper-right corner) and \"Jira board\"(\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  avg(lead_time/1440) as value\r\nfrom jira_issues ji\n  join jira_board_issues jbi on ji.issue_id = jbi.issue_id\r\nwhere \n  std_type = 'Bug'\n  and std_status = 'Resolved'\n  and $__timeFilter(resolution_date)\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Bug Age (day)",
   "type": "stat",
   "description": "1. The bug age at which 80% bugs‘ age lies below it.\n2. The bugs being calculated are filtered by \"bug resolution time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    ji.lead_time,\n    percent_rank() over (order by lead_time asc) as ranks\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Bug'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect\n  now() as time,\n  max(lead_time/1440) as value\r\nfrom _ranks\r\nwhere \n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Average Bug Age over Time",
   "type": "timeseries",
   "description": "1. The average and 80th percentile bug age over time.\n2. The time granularity can be switched to Week or Month by \"Time Interval\" above. \n3. When Time Interval is set to \"Month\", the average_bug_age of \"2021-06-01\" refers to the average age of bugs whose resolution time falls under [2020-06-01, 2020-07-01).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _bugs as(\n  select \n    ji.issue_id,\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\n    lead_time,\n    round(lead_time/1440) as lead_time_day\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Bug'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  timestamp(time) as time,\n  avg(lead_time/1440) as \"Average Lead Time\"\r\nfrom _bugs\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Bug Age (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of bug age. \n2. Each point refers to the percent rank of a bug age.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    round(ji.lead_time/1440) as lead_time_day\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Bug'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n  order by lead_time_day asc\n)\n\r\nselect \n  now() as time,\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "title": "Average Bug Age by Epic",
   "type": "barchart",
   "description": "The average time spent on fixing bugs under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "rawSql": "with _bugs as(\n  select\n    ji.issue_id,\n    ji.epic_key,\n    ji.lead_time\n  from\n    jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Bug'\n    and std_status = 'Resolved'\n    and epic_key is not null\n    and epic_key != ''\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  now() as time,\n  epic_key as \"Epic Key\",\n  avg(lead_time)/1440 as \"Bug Age\"\r\nfrom _bugs\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 135 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/4.png\" alt=\"No.4\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Operation<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Incident Age (day)",
   "type": "stat",
   "description": "1. The average incident age.\n2. Incident age refers to the length of time from incident creation to resolution.\n3. The incidents being calculated are filtered by \"incident resolution time\" (time filter at the upper-right corner) and \"Jira board\"(\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  avg(lead_time/1440) as value\r\nfrom jira_issues ji\n  join jira_board_issues jbi on ji.issue_id = jbi.issue_id\r\nwhere \n  std_type = 'Incident'\n  and std_status = 'Resolved'\n  and $__timeFilter(resolution_date)\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Incident Age (day)",
   "type": "stat",
   "description": "1. The incident age at which 80% incidents‘ age lies below it.\n2. The incidents being calculated are filtered by \"incident resolution time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    ji.lead_time,\n    percent_rank() over (order by lead_time asc) as ranks\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Incident'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect\n  now() as time,\n  max(lead_time/1440) as value\r\nfrom _ranks\r\nwhere \n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Average Incident Age over Time",
   "type": "timeseries",
   "description": "1. The average and 80th percentile incident age over time.\n2. The time granularity can be switched to Week or Month by \"Time Interval\" above. \n3. When Time Interval is set to \"Month\", the average_incident_age of \"2021-06-01\" refers to the average age of incidents whose resolution time falls under [2020-06-01, 2020-07-01).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _incidents as(\n  select \n    ji.issue_id,\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\n    lead_time,\n    round(lead_time/1440) as lead_time_day\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Incident'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  timestamp(time) as time,\n  avg(lead_time/1440) as \"Average Lead Time\"\r\nfrom _incidents\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Incident Age (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of incident age.\n2. Each point refers to the percent rank of a incident age.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    round(ji.lead_time/1440) as lead_time_day\n  from jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Incident'\n    and std_status = 'Resolved'\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n  order by lead_time_day asc\n)\n\r\nselect \n  now() as time,\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "title": "Average Incident Age by Epic",
   "type": "barchart",
   "description": "The average time spent on fixing incidents under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "rawSql": "with _incidents as(\n  select\n    ji.issue_id,\n    ji.epic_key,\n    ji.lead_time\n  from\n    jira_issues ji\n    join jira_board_issues jbi on ji.issue_id = jbi.issue_id\n  where \n    std_type = 'Incident'\n    and std_status = 'Resolved'\n    and epic_key is not null\n    and epic_key != ''\n    and $__timeFilter(resolution_date)\n    and jbi.board_id = $board_id\n)\n\r\nselect \n  now() as time,\n  epic_key as \"Epic Key\",\n  avg(lead_time)/1440 as \"Incident Age\"\r\nfrom _incidents\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  }
 ]
}