version: "3.8"
services:
  mysql-test:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=lake_test
      - MYSQL_USER=merico
      - MYSQL_PASSWORD=merico
      - TZ=UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-log-bin
    networks:
      - devlake-test-net
    healthcheck: # ADD THIS HEALTHCHECK
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Give it 30s to start up before first health check

  devlake-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DEVLAKE_PLUGINS: ""
    env_file:
      - ./.env
    environment:
      - DB_URL=mysql://merico:merico@mysql-test:3306/lake_test?charset=utf8mb4&parseTime=True&loc=UTC
      - DEVLAKE_PLUGINS=""
    depends_on:
      mysql-test: # CHANGE THIS
        condition: service_healthy # WAIT FOR MYSQL TO BE HEALTHY
    ports:
      - "8081:8080"
    networks:
      - devlake-test-net
    # Consider adding a restart policy if it might still fail occasionally
    # restart: unless-stopped

volumes:
  mysql-test-storage:

networks:
  devlake-test-net: