version: "3.8"
services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=lake
      - MYSQL_USER=merico
      - MYSQL_PASSWORD=merico
      - TZ=UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-log-bin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - devlake-net

  grafana:
    image: grafana/grafana:9.5.5
    image: grafana/grafana:9.5.5
    ports:
      - "3002:3000"
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - TZ=UTC
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - TZ=UTC
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - devlake-net

  devlake:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DEVLAKE_PLUGINS: ""
    volumes:
      - ./backend/core:/app/core
      - ./backend/helpers:/app/helpers
      - ./backend/impls:/app/impls
      - ./backend/plugins:/app/plugins # Mount plugin sources
      - ./backend/python:/app/python # Mount python sources within backend
      - ./backend/resources:/app/resources # Mount resources for editing
      - ./backend/scripts:/app/scripts
      - ./backend/server:/app/server
      - ./backend/test:/app/test
      - ./backend/go.mod:/app/go.mod
      - ./backend/go.sum:/app/go.sum
      - ./backend/Makefile:/app/Makefile
      - ./backend/DevelopmentManual.md:/app/DevelopmentManual.md
      - ./backend/swagger-stub.go:/app/swagger-stub.go
      - go-modules:/go/pkg/mod
      - devlake-log:/app/logs
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - DB_URL=mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC
      - LOGGING_DIR=/app/logs
      - GIN_MODE=debug
      - TZ=UTC
      - PLUGIN_DIR=bin/plugins
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - devlake-net

  config-ui:
    image: node:18-bookworm
    working_dir: /app
    volumes:
      - ./config-ui:/app
    image: node:18-bookworm
    working_dir: /app
    volumes:
      - ./config-ui:/app
    ports:
      - "4000:4000"
    restart: on-failure
      - "4000:4000"
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - DEVLAKE_ENDPOINT=localhost:8080
      - GRAFANA_ENDPOINT=http://localhost:3002
      - NODE_ENV=development
      - TZ=UTC
    depends_on:
      - devlake
    networks:
      - devlake-net
    command: sh -c "yarn install && yarn start"
    networks:
      - devlake-net
    command: sh -c "yarn install && yarn start"

volumes:
  mysql-storage:
  grafana-storage:
  devlake-log:
  go-modules:

networks:
  devlake-net:
  go-modules:

networks:
  devlake-net: