# docker-compose.dev.yml (Aligned with DevLake docs, focusing on backend build)
version: "3.8" # Version is fine, even if obsolete warning appears
services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-log-bin
    networks:
      - devlake-net

  grafana:
    image: grafana/grafana:9.5.5
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - TZ=UTC
    restart: always
    depends_on:
      - mysql
    networks:
      - devlake-net

  devlake: # Backend
    build:
      context: backend
      args:
        HTTPS_PROXY: "${HTTPS_PROXY}"
        GOPROXY: "${GOPROXY}"
    volumes:
      - ./backend:/app # Mount source code as per docs
      - go-modules:/go/pkg/mod
      - devlake-log:/app/logs
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - DB_URL=mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC
      - LOGGING_DIR=/app/logs
      - GIN_MODE=debug
      - TZ=UTC
    depends_on:
      - mysql
    networks:
      - devlake-net
    command: tail -f /dev/null # Keep alive for exec + 'make run' / 'air'

  config-ui: # Frontend - Using base Node image for dev
    image: node:18-bookworm # Match Node version if possible (from config-ui/Dockerfile builder stage)
    working_dir: /app
    volumes:
      - ./config-ui:/app # Mount source code
    ports:
      - 4000:4000 # Assuming Vite is configured for port 4000 (from package.json "start": "vite")
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - DEVLAKE_ENDPOINT=http://localhost:8080
      - GRAFANA_ENDPOINT=http://localhost:3002
      - NODE_ENV=development
      - TZ=UTC
      # Vite dev server usually listens on port 5173 by default.
      # If 'yarn start' (which runs 'vite') uses 5173 internally,
      # and you want to access it via host port 4000, change ports mapping:
      # ports:
      #  - "4000:5173"
      # Or, if vite.config.js in config-ui sets server.port = 4000, then "4000:4000" is fine.
      # Let's assume "4000:4000" based on the original compose file's exposure.
    depends_on:
      - devlake
    networks:
      - devlake-net
    command: sh -c "yarn install && yarn start" # 'start' is from config-ui/package.json

volumes:
  mysql-storage:
  grafana-storage:
  devlake-log:
  go-modules:

networks:
  devlake-net: