version: "3.8"
services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --skip-log-bin

  postgres:
    image: postgres:14.2
    volumes:
      - postgres-storage:/var/lib/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lake
      POSTGRES_USER: merico
      POSTGRES_PASSWORD: merico
      TZ: UTC

  grafana:
    image: grafana/grafana:9.5.5
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - TZ=UTC
    restart: always
    depends_on:
      - mysql

  devlake:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        HTTPS_PROXY: "${HTTPS_PROXY}"
        GOPROXY: "${GOPROXY}"
    ports:
      - 8080:8080
    restart: always
    volumes:
      - devlake-log:/app/logs
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - ./.env
    environment:
      LOGGING_DIR: /app/logs
      TZ: UTC
      # LOGOUT_URI: https://xxx.amazoncognito.com/logout?client_id=yyy&logout_uri=http%3A%2F%2Flocalhost%3A4180%2Foauth2%2Fsign_out
    depends_on:
      - mysql

  config-ui:
    image: node:18-bookworm
    working_dir: /app
    volumes:
      - ./config-ui:/app
    ports:
      - "4000:4000"
    restart: on-failure
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
      TZ: UTC
      #ADMIN_USER: devlake
      #ADMIN_PASS: letsdivein
    depends_on:
      - devlake
    networks:
      - devlake-net
    command: sh -c "yarn install && yarn start"

volumes:
  mysql-storage:
  grafana-storage:
  devlake-log:
  go-modules:

networks:
  devlake-net: