{
 "title": "Opsgenie",
 "time": { "from": "2021-06-05T21:00:42.390Z", "to": "2025-06-16T21:00:42.390Z" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select concat(name, '--', id) from boards where id like 'opsgenie%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the incident data from Opsgenie.\n- Data Source Required: Opsgenie"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Incident Resolution Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Incidents [Created in Selected Time Range]",
   "type": "stat",
   "description": "1. Total number of incidents created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Opsgenie board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct i.issue_key) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})\n"
    }
   ]
  },
  {
   "title": "Number of Resolved Incidents [Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct i.issue_key) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  i.original_status = 'resolved'\n  and $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})\n"
    }
   ]
  },
  {
   "title": "List of Incidents [Created in Selected Time Range]",
   "type": "table",
   "description": "1. Total number of incidents created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "select \n  i.title as \"Title\",\n  i.issue_key as \"Id\",\n  group_concat(b.name separator \", \") as \"Service(s)\",\n  i.description as \"Description\",\n  i.original_status as \"Original Status\",\n  i.priority as \"Priority\",\n  i.created_date as \"Created Date\",\n  i.updated_date as \"Updated Date\",\n  round((i.lead_time_minutes/1440),1) as \"Lead Time Days\",\n  i.url as \"URL\"\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\n  join boards b on bi.board_id = b.id\r\nwhere \n  $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})\r\nGROUP BY i.title, i.issue_key, i.description, i.original_status, i.priority, i.created_date, i.updated_date, i.lead_time_minutes, i.url"
    }
   ]
  },
  {
   "title": "Number of Closed Incidents [Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct i.issue_key) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  i.original_status = 'closed'\n  and $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})\n"
    }
   ]
  },
  {
   "title": "Incident Resolution Rate [Incidents created in the selected time range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _requirements as(\n  select\n    count(distinct i.id) as total_count,\n    count(distinct case when i.original_status = 'resolved' then i.id else null end) as resolved_count\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    $__timeFilter(i.created_date)\n    and bi.board_id in (${board_id})\n)\n\r\nselect \n  now() as time,\n  1.0 * resolved_count/total_count as requirement_delivery_rate\r\nfrom _requirements"
    }
   ]
  },
  {
   "title": "Incident Resolution Rate over Time [Incidents Created in Selected Time Range]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\n  select\n    DATE_ADD(date(i.created_date), INTERVAL -DAYOFMONTH(date(i.created_date))+1 DAY) as time,\n    1.0 * count(distinct case when i.original_status = 'resolved' then i.id else null end)/count(distinct i.id) as resolved_rate\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    $__timeFilter(i.created_date)\n    and bi.board_id in (${board_id})\n  group by 1\n)\n\r\nselect\n  time,\n  resolved_rate\r\nfrom _requirements\r\norder by time"
    }
   ]
  },
  {
   "title": "2. Mean Time to Resolve (MTTR)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MTTR [Incidents Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  avg(lead_time_minutes/1440) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  i.original_status = 'resolved'\n  and $__timeFilter(i.resolution_date)\n  and bi.board_id in (${board_id})"
    }
   ]
  },
  {
   "title": "80% Incidents' MTTR are less than # [Incidents Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    i.lead_time_minutes,\n    percent_rank() over (order by lead_time_minutes asc) as ranks\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.original_status = 'resolved'\n    and $__timeFilter(i.resolution_date)\n    and bi.board_id in (${board_id})\n)\n\r\nselect\n  max(lead_time_minutes/1440) as value\r\nfrom _ranks\r\nwhere \n  ranks <= 0.8"
    }
   ]
  },
  {
   "title": "Mean MTTR [Incidents Resolved in Select Time Range]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\n  select \n    DATE_ADD(date(i.resolution_date), INTERVAL -DAYOFMONTH(date(i.resolution_date))+1 DAY) as time,\n    avg(lead_time_minutes/1440) as mean_incident_age\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.original_status = 'resolved'\n    and $__timeFilter(i.resolution_date)\n    and bi.board_id in (${board_id})\n  group by 1\n)\n\r\nselect \n  date_format(time,'%M %Y') as month,\n  mean_incident_age\r\nfrom _requirements\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Cumulative Distribution of MTTR [Incidents Resolved in Select Time Range]",
   "type": "graph",
   "description": "1. The cumulative distribution of MTTR\n2. Each point refers to the percent rank of a distinct duration to resolve incidents.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    round(i.lead_time_minutes/1440) as lead_time_day\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.original_status = 'resolved'\n    and $__timeFilter(i.resolution_date)\n    and bi.board_id in (${board_id})\n  order by lead_time_day asc\n)\n\r\nselect \n  now() as time,\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  },
  { "title": "3. Incident Responders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "List of Incident Responder [organized in JSON format]",
   "type": "table",
   "description": "Due to Opsgenie API limitation regarding the relationship between assignee, users, and incident (and lack of 'assign at' key ), the column assignee represents a JSON object containing all assignee from said incident",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select \n  i.title as \"Incident Name\",\n  concat('[', group_concat(concat('{\"name\": \"', a.assignee_name, '\"', ', \"type\": \"', r.type, '\"}') separator \", \"), ']') as \"Responders\"\nfrom issues as i\n  inner join issue_assignees as a on (substring_index(i.id, \":\", -1) = substring_index(a.issue_id, \":\", -1))\n  inner join _tool_opsgenie_responders as r on a.assignee_id = r.id\nwhere i.id like 'opsgenie%'\ngroup by i.title;"
    }
   ]
  }
 ]
}