{
 "title": "Teambition",
 "tags": [ "Data Source Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select concat(name, '--', id) from boards where id like 'teambition%'"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "select distinct type from issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic project management metrics from Teambition.\n- Data Source Required: Teambition"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Issue Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Issues [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "1. Total number of issues created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  count(distinct i.id) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  i.type in (${type})\n  and $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})"
    }
   ]
  },
  {
   "title": "Number of Delivered Issue [Issues Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  count(distinct i.id) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  i.type in (${type})\n  and i.status = 'DONE'\n  and $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})"
    }
   ]
  },
  {
   "title": "Issue Status Distribution over Month [Issues Created in Selected Time Range]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_ADD(date(i.created_date), INTERVAL -DAYOFMONTH(date(i.created_date))+1 DAY) as time,\n  count(distinct case when status != 'DONE' then i.id else null end) as \"Number of Open Issues\",\n  count(distinct case when status = 'DONE' then i.id else null end) as \"Number of Delivered Issues\"\r\nFROM issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\r\nwhere \n  i.type in (${type})\n  and $__timeFilter(i.created_date)\n  and bi.board_id in (${board_id})\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _requirements as(\n  select\n    count(distinct i.id) as total_count,\n    count(distinct case when i.status = 'DONE' then i.id else null end) as delivered_count\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.type in (${type})\n    and $__timeFilter(i.created_date)\n    and bi.board_id in (${board_id})\n)\n\r\nselect \n  now() as time,\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirements"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate over Time [Issues Created in Selected Time Range]",
   "type": "timeseries",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\n  select\n    DATE_ADD(date(i.created_date), INTERVAL -DAYOFMONTH(date(i.created_date))+1 DAY) as time,\n    1.0 * count(distinct case when i.status = 'DONE' then i.id else null end)/count(distinct i.id) as delivered_rate\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.type in (${type})\n    and $__timeFilter(i.created_date)\n    and bi.board_id in (${board_id})\n  group by 1\n)\n\r\nselect\n  time,\n  delivered_rate\r\nfrom _requirements\r\norder by time"
    }
   ]
  },
  {
   "title": "2. Issue Lead Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Issue Lead Time in Days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  avg(lead_time_minutes/1440) as value\r\nfrom issues i\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \n  i.type in (${type})\n  and i.status = 'DONE'\n  and $__timeFilter(i.resolution_date)\n  and bi.board_id in (${board_id})"
    }
   ]
  },
  {
   "title": "80% Issues' Lead Time are less than # days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    i.lead_time_minutes,\n    percent_rank() over (order by lead_time_minutes asc) as ranks\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.type in (${type})\n    and i.status = 'DONE'\n    and $__timeFilter(i.resolution_date)\n    and bi.board_id in (${board_id})\n)\n\r\nselect\n  max(lead_time_minutes/1440) as value\r\nfrom _ranks\r\nwhere \n  ranks <= 0.8"
    }
   ]
  },
  {
   "title": "Mean Issue Lead Time [Issues Resolved in Select Time Range]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\n  select \n    DATE_ADD(date(i.resolution_date), INTERVAL -DAYOFMONTH(date(i.resolution_date))+1 DAY) as time,\n    avg(lead_time_minutes/1440) as mean_lead_time\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.type in (${type})\n    and i.status = 'DONE'\n    and $__timeFilter(i.resolution_date)\n    and bi.board_id in (${board_id})\n  group by 1\n)\n\r\nselect \n  date_format(time,'%M %Y') as month,\n  mean_lead_time\r\nfrom _requirements\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Cumulative Distribution of Requirement Lead Time [Issues Resolved in Select Time Range]",
   "type": "graph",
   "description": "1. The cumulative distribution of requirement lead time. \n2. Each point refers to the percent rank of a lead time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    round(i.lead_time_minutes/1440) as lead_time_day\n  from issues i\n    join board_issues bi on i.id = bi.issue_id\n  where \n    i.type in (${type})\n    and i.status = 'DONE'\n    and $__timeFilter(i.resolution_date)\n    and bi.board_id in (${board_id})\n  order by lead_time_day asc\n)\n\r\nselect \n  now() as time,\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}